'use client';
import { useState } from 'react';
import dynamic from 'next/dynamic';
const Spirit = dynamic(() => import('./spirit'), { ssr: false });
export default function Home() {
 const [mode, setMode] = useState<'blossom'|'moonlight'>('blossom');
 const [motion, setMotion] = useState(true);
 return <main data-theme={mode}>
 <a className="skip" href="#about">Skip to content</a>
 <header><a href="#" className="logo" aria-label="Akshay Gupta home"><span className="sigil">✧</span> AKSHAY<span className="logo-dot">.</span></a><nav aria-label="Main navigation"><a href="#about">The human</a><a href="#playground">The magic</a><a href="https://github.com/akshaycg46" target="_blank" rel="noreferrer">GitHub ↗</a></nav><a className="nav-contact" href="#connect">Let’s connect <span>↗</span></a></header>
 <section className="hero" aria-labelledby="hero-title">
 <div className="hero-art"><img src="/personal/ahri-hero.webp" alt="Ahri surrounded by flowing luminous tails, holding a blue spirit orb" fetchPriority="high"/><div className="art-shade"/></div>
 <div className="hero-content"><div className="eyebrow"><i/> A LITTLE LOGIC. A LITTLE MAGIC.</div><h1 id="hero-title">Akshay<br/><em>Gupta.</em></h1><p className="hero-sub">Computer science student.<br/>UCF Knight. Always curious.</p><p className="intro">Exploring the space where code meets imagination.<br className="desktop"/> Welcome to my corner of the digital world.</p><a className="button" href="#about">Step into my world <span>↗</span></a><a className="text-link" href="https://github.com/akshaycg46" target="_blank" rel="noreferrer">Find me on GitHub <span>↗</span></a></div>
 <div className="vertical-note">INSPIRED BY AHRI · MADE OF CURIOSITY</div>
 <div className="art-label"><span className="tiny-star">✧</span><div>THE NINE-TAILED MUSE<small>Ahri / Spirit Blossom</small></div></div>
 <div className="hero-bottom"><span>01 — THE INTRODUCTION</span><a href="#about">SCROLL TO EXPLORE <span>↓</span></a><span>ORLANDO, FL <i className="live-dot"/></span></div>
 </section>
 <div className="ribbon"><span>COMPUTER SCIENCE</span><b>✧</b><span>UNIVERSITY OF CENTRAL FLORIDA</span><b>✧</b><span>CODE × CURIOSITY</span><b>✧</b><span>AHRI MAIN ENERGY</span></div>
 <section id="about" className="about section"><div className="section-label">02 / THE HUMAN BEHIND THE SCREEN</div><div className="about-grid"><h2>A curious mind.<br/><em>A creative spirit.</em></h2><div><p className="large-copy">Hey, I’m Akshay — a Computer Science student at the University of Central Florida.</p><p>I’m drawn to the possibilities of technology: taking an idea, figuring out how it works, and making something you can actually interact with. This space is a little introduction to me, and a place to keep building.</p><p>And when it comes to inspiration? Ahri brings the magic. Her spirit-world aesthetic is woven into every corner of this site.</p><div className="facts"><div><small>STUDYING</small><strong>Computer Science</strong></div><div><small>HOME BASE</small><strong>UCF · Orlando</strong></div><div><small>PLAYER SELECT</small><strong>Ahri, of course</strong></div></div></div></div></section>
 <section id="playground" className="playground section"><div className="section-label">03 / A LITTLE EXPERIMENT</div><div className="play-grid"><div className="play-copy"><span className="pill">LIVE 3D EXPERIENCE</span><h2>Follow your<br/><em>own orbit.</em></h2><p>A small piece of the spirit realm, brought to life in your browser. Move your pointer or drag across the orb to change its perspective.</p><div className="theme-controls" role="group" aria-label="Spirit color"><button aria-pressed={mode==='blossom'} onClick={()=>setMode('blossom')}><i className="swatch purple"/>Spirit blossom</button><button aria-pressed={mode==='moonlight'} onClick={()=>setMode('moonlight')}><i className="swatch blue"/>Moonlight</button></div><button className="motion-control" aria-pressed={!motion} onClick={()=>setMotion(!motion)}>{motion?'Ⅱ Pause motion':'▷ Resume motion'}</button></div><div className="orb-frame"><Spirit color={mode==='blossom'?'#bd91ff':'#7ddfff'} motion={motion}/><span className="orb-caption">ORB OF POSSIBILITY <span>✧</span> INTERACTIVE / 001</span></div></div></section>
 <section id="connect" className="connect section"><div className="section-label">04 / THE NEXT CHAPTER</div><p>Great things start with a little curiosity.</p><h2>Let’s build<br/><em>something magic.</em></h2><a className="button" href="https://github.com/akshaycg46" target="_blank" rel="noreferrer">Meet me on GitHub <span>↗</span></a></section>
 <footer><a className="logo" href="#"><span className="sigil">✧</span> AKSHAY.</a><span>© {new Date().getFullYear()} Akshay Gupta</span><span>BUILT WITH NEXT.JS & A LITTLE SPIRIT</span><a href="#">Back to top ↑</a></footer><div className="fan-note">Independent fan-inspired portfolio. Ahri and League of Legends belong to Riot Games. Not affiliated with or endorsed by Riot Games.</div>
 </main>
}
